views_send.settings:
  type: config_object
  label: 'Views Send Settings'
  mapping:
    throttle:
      type: integer
      label: 'Number of messages sent per cron run'
    retry:
      type: integer
      label: 'How many retries before a message in the spool is discarded'
    spool_expire:
      type: integer
      label: 'How many days messages are retained in the spool after successful sending'
    debug:
      type: boolean
      label: 'Log all outgoing email messages in the system log'
